version: '3'

services:
 camp_collector:
  image: haze5959/camp_collector:0.1
  network_mode: "host"
  privileged: true
  command: bash -c "cd CampingCrawler_Collector && git pull && python3 -u  main.py"
